// GENERATED by @edgedb/generate v0.4.1

import * as $ from "../reflection";
import * as _ from "../imports";
import type * as _std from "./std";
import type * as _auth from "./ext/auth";
export type $UserλShape = $.typeutil.flatten<_std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588λShape & {
  "identity": $.LinkDesc<_auth.$Identity, $.Cardinality.One, {}, false, false,  false, false>;
  "name": $.PropertyDesc<_std.$str, $.Cardinality.One, false, false, false, false>;
}>;
type $User = $.ObjectType<"default::User", $UserλShape, null, [
  ..._std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588['__exclusives__'],
]>;
const $User = $.makeType<$User>(_.spec, "e70fc2df-7e29-11ee-a3da-2b5858cec2aa", _.syntax.literal);

const User: $.$expr_PathNode<$.TypeSet<$User, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($User, $.Cardinality.Many), null);

export type $current_userλShape = $.typeutil.flatten<$UserλShape & {
}>;
type $current_user = $.ObjectType<"default::current_user", $current_userλShape, null, [
  ...$User['__exclusives__'],
]>;
const $current_user = $.makeType<$current_user>(_.spec, "e840cc83-7f10-11ee-83ed-cda32a28d566", _.syntax.literal);

const current_user: $.$expr_PathNode<$.TypeSet<$current_user, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($current_user, $.Cardinality.Many), null);

export type $identityλShape = $.typeutil.flatten<_auth.$IdentityλShape & {
}>;
type $identity = $.ObjectType<"default::identity", $identityλShape, null, [
  ..._auth.$Identity['__exclusives__'],
]>;
const $identity = $.makeType<$identity>(_.spec, "927b6fd4-7eef-11ee-9ac7-f7a5d99a3690", _.syntax.literal);

const identity: $.$expr_PathNode<$.TypeSet<$identity, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($identity, $.Cardinality.Many), null);

const $default__globals: {  current_user: _.syntax.$expr_Global<
              // "default::current_user",
              $current_user,
              $.Cardinality.AtMostOne
              >,  identity: _.syntax.$expr_Global<
              // "default::identity",
              $identity,
              $.Cardinality.AtMostOne
              >} = {  current_user: _.syntax.makeGlobal(
              "default::current_user",
              $.makeType(_.spec, "e840cc83-7f10-11ee-83ed-cda32a28d566", _.syntax.literal),
              $.Cardinality.AtMostOne) as any,  identity: _.syntax.makeGlobal(
              "default::identity",
              $.makeType(_.spec, "927b6fd4-7eef-11ee-9ac7-f7a5d99a3690", _.syntax.literal),
              $.Cardinality.AtMostOne) as any};



export { $User, User, $current_user, current_user, $identity, identity };

type __defaultExports = {
  "User": typeof User;
  "current_user": typeof current_user;
  "identity": typeof identity;
  "global": typeof $default__globals
};
const __defaultExports: __defaultExports = {
  "User": User,
  "current_user": current_user,
  "identity": identity,
  "global": $default__globals
};
export default __defaultExports;
